### PR TITLE
Remove Python 3.3 because pkg_resources does not support it anymore

### PR DESCRIPTION
**Pull request by nickdirienzo**
Hopefully this fixes CI 🤞

### CODE REVIEW

**Comment by nickdirienzo** [comment]
@joealcorn friendly ping for a review if you have a moment. Thanks!

**Comment by crccheck** [comment]
Should the README be updated too?

> with support for Python 2.7, 3.3+

**Comment by nickdirienzo** [comment]
Thanks for the feedback @crccheck! I missed those places. I also updated `setup.py` as well to remove the reference to 3.3.

**Comment by joealcorn** [comment]
Thanks for bringing my attention to this!
Rather than remove support for 3.3 just because setuptools has, I've fixed the CI config to install the latest working version of setuptools when using python 3.3 with commit https://github.com/joealcorn/laboratory/commit/4569442bacd487354632bc0db1b20ea9099325fc

**Pull request closed without merging**
