### PR TITLE
ExperimentMixin class

### PR DESCRIPTION
**Pull request by mclate**
PR presents `ExperimentMixin` to let user easily inject `Experiment` into existing classes.

### CODE REVIEW

**Comment by mclate** [comment]
Hi. I've bumped into this nice project and thought i would be able to use it in future and decided to contribute one thing that might be useful. Let me know if i missed something and whether this is worthy being added to the package.

**Comment by joealcorn** [comment]
Hi, thanks for this PR! I'm going to give it a proper look over when I get some time.

**Comment by joealcorn** [comment]
I'm not sure I understand the use case behind this, why the need to integrate with existing classes?

I think you might be better served subclassing `Experiment` and using that as a decorator instead.

```python
class MyExperiment(Experiment):
    def compare(self, control, observation):
        return control == observation

    def publish(self, result):
        context = self.get_context()
        Stats().save(context=context, match=result.match)


class MyClass(object):
    def candidate_function(self, arg):
        return arg

    @MyExperiment(candidate=candidate_function)
    def control_function(self, arg):
        return arg
```

**Comment by mclate** [comment]
Well, guess it wasn't very clear for me from the documentation that one can do it this way. `Experiment` as decorator does make more sense. It might be good to add this as an example in the documentation.

**Comment by joealcorn** [comment]
You're right, the docs probably don't place enough emphasis on the decorator. Will touch up the docs when I get time. Thank you!

**Pull request closed without merging**
